TrajectoryPlannerROS:

  holonomic_robot: false
  sim_time: 1.0
  meter_scoring: false
  pdist_scale: 0.25
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.05
  controller_frequency: 5
  acc_lim_x: 2
  acc_lim_y: 2
  acc_lim_theta: 2
  max_vel_x: 1.0
  min_vel_x: 0.05
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 1.0

