TrajectoryPlannerROS:

  holonomic_robot: false
  sim_time: 1.0
  meter_scoring: false
  pdist_scale: 0.25
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  controller_frequency: 5
  acc_lim_x: 3
  acc_lim_y: 3
  acc_lim_theta: 3
  max_vel_x: 0.8
  min_vel_x: 0.08
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.25

