map_type: costmap

obstacle_range: 4.5
raytrace_range: 10.0

transform_tolerance: 0.2

inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /robond_bot/laser/scan, marking: true, clearing: true}
